### ISSUE TITLE
Trying to edit entities in the Map editor doesn't work. 

### ISSUE THREAD

**Issue by RaoKurai** [audinowho/PMDODump#103]
Trying to manipulate entities in the Map Editor only throws errors. 

Said error looks like this (Specifically when attempting to select an entity): 

`[2022/05/30 17:03:18.914] Serializing delegates is not supported on this platform.
Exception Depth: 0
System.Runtime.Serialization.SerializationException: Serializing delegates is not supported on this platform.
   at System.MulticastDelegate.GetObjectData(SerializationInfo info, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, BinaryFormatterWriter serWriter)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at RogueEssence.Dev.ReflectionExt.SerializeCopy[T](T obj)
   at RogueEssence.Dev.StateUndo'1.Apply()
   at RogueEssence.Dev.UndoStack.Apply(Undoable step)
   at RogueEssence.Dev.ViewModels.MapTabEntitiesViewModel.RemoveEntity(Character ent)
   at RogueEssence.Dev.ViewModels.MapTabEntitiesViewModel.OperateOnEntityAt(Loc position, EntityOp op)
   at RogueEssence.Dev.ViewModels.MapTabEntitiesViewModel.RemoveEntityAt(Loc position)
   at RogueEssence.Dev.ViewModels.MapTabEntitiesViewModel.PlaceEntity(Loc position)
   at RogueEssence.Dev.ViewModels.MapTabEntitiesViewModel.ProcessInput(InputManager input)
   at RogueEssence.Dev.ViewModels.MapEditViewModel.ProcessInput(InputManager input)
   at RogueEssence.GameManager.UpdateMeta()
   at RogueEssence.GameBase.Update(GameTime gameTime)`

![PMDO_A11j3Z2CxB](https://user-images.githubusercontent.com/73971155/171063184-3744a2c3-0a18-4f3a-9037-bb9f54724cad.png)

**Comment by audinowho** [comment]
Fix in https://github.com/RogueCollab/RogueEssence/commit/ea3d956603ce8cc6e756f5e094598d82a5485cae
