### ISSUE TITLE
Thief/Shadow Force's particle effect does not load properly

### ISSUE THREAD

**Issue by Shitpost-Sunkern** [audinowho/PMDODump#3]
Steps to reproduce:

1. Enter any dungeon
2. Find a foe and use Thief on that foe
3. A debug magenta checkerboard texture will appear instead of a particle effect. The following error will be printed to the console:

```
Exception Depth: 0
System.Exception: Error loading /[PATH]/PMDO/Content/Particle/Shadow_Force_Hit.dir

 ---> System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt32()
   at RogueEssence.Content.DirSheet.Load(BinaryReader reader)
   at RogueEssence.Content.GraphicsManager.GetAttackSheet(String name)
   --- End of inner exception stack trace ---

Exception Depth: 1
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt32()
   at RogueEssence.Content.DirSheet.Load(BinaryReader reader)
   at RogueEssence.Content.GraphicsManager.GetAttackSheet(String name)
```

**Comment by audinowho** [comment]
Fix in
https://github.com/audinowho/PMDODump/commit/083eeb17557988764dd88807a227e974bab5a6c5
